# Generated by Django 4.0 on 2021-12-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(null=True, upload_to='profile/thumbnail'),
        ),
    ]
